# Docker Compose error-pages

version: '3.7'

services:
  error-pages:
    image: tarampampam/error-pages:latest
    environment:
      TEMPLATE_NAME: matrix
      SHOW_DETAILS: "true"
    ports:
      - '8080:8080'